services:
  scraper:
    build: 
      context: ./headless-browser
      dockerfile: Dockerfile
    image: scraper:latest
    container_name: scraper
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - awt
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    restart: always
    volumes:
      - ./backend/database.db:/usr/src/app/database.db
    ports:
      - "3000:3000"
    networks:
      - awt
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - awt
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:awt
    ports:
      - "80:80"
    networks:
      - awt
networks:
  awt:
    driver: bridge
