openapi: 3.0.0
info:
  title: Message API
  version: 1.0.0
  description: API to manage and retrieve messages from the database.
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /messages:
    post:
      summary: Add a new message to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: integer
                  format: int64
                  example: 1625077800
                destination:
                  type: string
                  example: gnb.logs
                payload:
                  type: string
                  example: '{"message": "Log entry"}'
      responses:
        '201':
          description: Message added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Message added successfully
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid payload
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error message
    get:
      summary: Get messages from the database based on topic and time interval
      parameters:
        - name: topic
          in: query
          required: true
          schema:
            type: string
            enum: [telemetry, health, logs]
        - name: timeStart
          in: query
          schema:
            type: integer
            format: int64
            example: 1625077800
        - name: timeEnd
          in: query
          schema:
            type: integer
            format: int64
            example: 1625081400
        - name: limit
          in: query
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: integer
                      format: int64
                      example: 1625077800
                    destination:
                      type: string
                      example: gnb.logs
                    payload:
                      type: object
                      example: {"message": "Log entry"}
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Missing required parameter: topic'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error message
  /gnb/logs:
    get:
      summary: Get log messages from the database within a specified time interval
      parameters:
        - name: timeStart
          in: query
          schema:
            type: integer
            format: int64
            example: 1625077800
        - name: timeEnd
          in: query
          schema:
            type: integer
            format: int64
            example: 1625081400
        - name: limit
          in: query
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: List of log messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: integer
                      format: int64
                      example: 1625077800
                    destination:
                      type: string
                      example: gnb.logs
                    payload:
                      type: object
                      example: {"message": "Log entry"}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error message
    post:
      summary: Add a new log message to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: integer
                  format: int64
                  example: 1625077800
                message:
                  type: string
                  example: "Log entry"
      responses:
        '201':
          description: Log message added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  id:
                    type: integer
                    example: 123
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error message
  /cn5g/telemetry:
    get:
      summary: Get health data from the database within a specified time interval
      parameters:
        - name: timeStart
          in: query
          schema:
            type: integer
            format: int64
            example: 1625077800
        - name: timeEnd
          in: query
          schema:
            type: integer
            format: int64
            example: 1625081400
        - name: limit
          in: query
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: List of health data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: integer
                      format: int64
                      example: 1625077800
                    destination:
                      type: string
                      example: cn5g.telemetry
                    payload:
                      type: object
                      example: {"healthStatus": "Good"}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error message
    post:
      summary: Add a new health message to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: integer
                  format: int64
                  example: 1625077800
                healthStatus:
                  type: string
                  example: "Good"
      responses:
        '201':
          description: Health message added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Message added successfully
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error message
  /gnb/telemetry:
    get:
      summary: Get telemetry data from the database and filter by UE IDs
      parameters:
        - name: timeStart
          in: query
          schema:
            type: integer
            format: int64
            example: 1625077800
        - name: timeEnd
          in: query
          schema:
            type: integer
            format: int64
            example: 1625081400
        - name: ueIds
          in: query
          schema:
            type: string
            example: "1,2,3"
        - name: limit
          in: query
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: List of telemetry data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: integer
                      format: int64
                      example: 1625077800
                    destination:
                      type: string
                      example: gnb.telemetry
                    payload:
                      type: object
                      example: {"ues": [{"ueId": 1, "data": "telemetry data"}]}
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Error message
    post:
      summary: Add a new telemetry message to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: integer
                  format: int64
                  example: 1625077800
                ues:
                  type: array
                  items:
                    type: object
                    properties:
                      ueId:
                        type: integer
                        example: 1
                      data:
                        type: string
                        example: "telemetry data"
      responses:
        '201':
          description: Telemetry message added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Message added successfully
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema: